version: '3.4'

services:
  api-autenticacao:
    image: api-autenticacao
    build:
      context: .
    environment: 
      MYSQL_SERVER: ${MYSQL_SERVER}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PWD: ${MYSQL_PWD}
      MYSQL_SSL_MODE: ${MYSQL_SSL_MODE}
    ports:
      - "8080:80"
